Fix force close when go to userprofile
Fix :
 java.lang.RuntimeException: Could not deserialize object. Class com.bangkit.fishery_app.ui.screen.authentication.model.UserData does not define a no-argument constructor. If you are using ProGuard, make sure these constructors are not stripped
Signed-off-by: arifamsar <dcylert@gmail.com>